name: flutter_music_player
description: A simple Flutter music player for web.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
